# netlify.toml

[build]
  # No build command needed for a plain HTML/CSS/JS site
  command = ""
  # Publish the folder where your index.html lives, relative to repo root
  publish = "typing-game/Typing_Game"

# (Optional) Uncomment this section if you ever need SPA-style redirects:
# [[redirects]]
#   from = "/*"
#   to   = "/index.html"
#   status = 200

# (Optional) Configuration for Netlify Dev
# [dev]
#   command = "npm start"
#   port    = 3000
#   publish = "typing-game/Typing_Game"
